[project]
name = "helixdb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chonkie>=1.0.8",
    "docling>=2.15.1",
    "helix-py>=0.2.2",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]
